version: 2
jobs:
  build:
    machine: true    
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - OS=linux
      - ARCH=amd64
    steps:
      - checkout
      - run:
          name: update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: make test
      - deploy:
          command: |
            # if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              echo $ACCT_AUTH > ${HOME}/gcloud-service-key.json              
              git config --global user.email "ci@gochain.io"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              make release
            # fi